SUPABASE_URL  = "https://qbmccrnndaawvackvwhk.supabase.co"
SUPABASE_KEY  = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFibWNjcm5uZGFhd3ZhY2t2d2hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzU3NjMsImV4cCI6MjA2ODUxMTc2M30.1ZND-25O4SMocgUqZk6wucOwunNOkrJsJVrqobMnM2c"
ADMIN_USERNAME = "admin"
# bcrypt hash for a strong password:  bcrypt.hashpw("Your$trongP@ss".encode(), bcrypt.gensalt()).decode()
ADMIN_PWD_HASH = "$2b$12$u7N6…"
