[supabase]
url = "https://qbmccrnndaawvackvwhk.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFibWNjcm5uZGFhd3ZhY2t2d2hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzU3NjMsImV4cCI6MjA2ODUxMTc2M30.1ZND-25O4SMocgUqZk6wucOwunNOkrJsJVrqobMnM2c"

[admin]
username = "madhavarapuchandrasekhara@gmail.com"
password = "pragati$123"
